import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import store from "@/redux/store";
import { Provider } from "react-redux";
import Providers from "@/providers";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {" "}
          <Toaster position="top-right" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
